version: '3'

services:
  music-tag:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    container_name: music-tag-web
    ports:
      - "8001:8001"
    volumes:
      - /你的音乐文件夹路径:/app/media:rw
    restart: unless-stopped