version: '3'

services:
  music-tag:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    container_name: music-tag-web
    environment:
      - SITE_LOGIN=false
    ports:
      - "8001:8001"
    volumes:
      - /vol1/1000/music:/app/media:rw
      - ./data:/app/data
    restart: unless-stopped